#!/usr/bin/env python3

"""Properties for charnet project"""

import tempfile

# Directory containing Charnet data.
CHARNET_DATA_DIRECTORY = 'data/'

# Directory containing Stanford GraphBase data.
SGB_DATA_DIRECTORY = 'sgb_data/'

# System
DEFAULT_OUTPUT_DIRECTORY = tempfile.gettempdir()

# csv files
CSV_FIELDS_SEPARATOR = ','

# Graphs
GRAPH_EDGE_SYMBOL = '--'

class Project():
    """Project contains information about where to write the
    files generating during the calculation and plotting."""
    # Where to store files generated by the scripts.
    out_dir = DEFAULT_OUTPUT_DIRECTORY
    def __init__(self):
        return
    # Template for specific project configurations.
    @staticmethod
    def get_data_dir():
        '''Return the directory containing data for the project.'''
        return 'data/'
    @staticmethod
    def get_out_dir():
        """Return the directory to write the files."""
        return Project.get_out_dir
    @staticmethod
    def set_outdir(directory):
        """Set the directory to write the files."""
        Project.out_dir = directory
